name: Unittests
on: [pull_request, workflow_dispatch]
jobs:

  macos:
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: python -m pip install -r requirements.txt
      - name: Run unit tests
        run: python run_all_tests.py -a
